# Generated by Django 3.0.3 on 2020-05-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('movieName', models.CharField(max_length=50)),
                ('movieType', models.CharField(max_length=50)),
                ('movieLanguage', models.CharField(max_length=50)),
                ('movieCast', models.CharField(max_length=50)),
                ('movieDirector', models.CharField(max_length=50)),
                ('movieDuration', models.CharField(max_length=50)),
                ('movieReleaseDate', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'movie_22344',
            },
        ),
    ]
