# Generated by Django 3.0.6 on 2020-05-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTBApp', '0002_movie_movieimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custId', models.AutoField(primary_key=True, serialize=False)),
                ('custName', models.CharField(max_length=50)),
                ('custEmailId', models.CharField(max_length=50)),
                ('custPassword', models.CharField(max_length=50)),
                ('custContactNo', models.IntegerField(max_length=10)),
                ('custAddress', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cust_22344',
            },
        ),
    ]
