# Generated by Django 3.0.6 on 2020-05-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTBApp', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='custContactNo',
            field=models.CharField(max_length=20),
        ),
    ]
