# Generated by Django 3.0.6 on 2020-05-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTBApp', '0004_auto_20200510_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminEmailId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adminPassword', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'admin_22344',
            },
        ),
    ]
