# Generated by Django 3.0.6 on 2020-05-31 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OMTBApp', '0006_shows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('bookedSeats', models.CharField(max_length=100)),
                ('totalPrice', models.FloatField(max_length=50)),
                ('bookingDate', models.CharField(max_length=50)),
                ('bookingStatus', models.CharField(default='Processing', max_length=50)),
                ('bookedShow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMTBApp.Shows')),
            ],
            options={
                'db_table': 'booking_22344',
            },
        ),
    ]
