# Generated by Django 3.0.6 on 2020-05-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTBApp', '0007_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='custEmailId',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
